language: node_js
node_js:
  - 8
env:
  - CI=true  
cache:
  directories:
    - node_modules
script:
  - npm run build
  - npm test
notifications:
  webhooks: https://flooo.me/travis/designhub-dev.php
before_install:
 - sudo apt-get install lftp
deploy:
  provider: script
  script: sh deploy.sh
  skip_cleanup: true