language: node_js
node_js:
  - 8
env:
  - CI=true  
cache:
  directories:
    - node_modules
script:
  - npm run build
  - npm test
notifications:
  webhooks: https://flooo.me/travis/designhub-dev.php
deploy:
  provider: script
  script: deploy.sh