language: node_js
node_js:
  - 8
env:
  - CI=true  
cache:
  directories:
    - node_modules
script:
  - npm run build
  - npm test
notifications:
  webhooks: https://flooo.me/travis/designhub-dev.php
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: build/
  on:
    branch: master
after_success:
    "curl --ftp-create-dirs -T build -u $FTP_USER:$FTP_PASS ftp://$FTP_HOST"
